### ISSUE TITLE
prepare data failed

### ISSUE THREAD

**Issue by xinq2016** [rizar/attention-lvcsr#11]
Hi Dzmitry,

I wanna build the attention-lvcsr for mandarin of my own data set.
But there is an issue in the data prepare for the hd5file.
There are 107429 characters in the tmp_chars, when creates dataset attribute, there is a RuntimeError: Unable to create attribute (Object header message is too large)
How can I fix it?

Many thanks

**Comment by rizar** [comment]
@xinq2016 , you might have hit a fundamental limitation of hdf5 format.

Please note, that this repository is only released for the purpose of reproducing the experiments from the paper. Unfortunately, I don't have time to help people to run their own experiments on different datasets with this code. Sorry for that.
