### ISSUE TITLE
Training with CUDA?

### ISSUE THREAD

**Issue by Elecky** [rizar/attention-lvcsr#14]
Hello.
Does this project support training with CUDA?
When I train this model, I first received the error "mo module pygpu", to solve this, I installed libgpuarray and pygpu manually. After that I tried again, but I then received the error "wrong major API version for gpuarray: 1, make sure Theano and libgpuarray/pygpu are in sync ".
I'm using the latest version of libgpuarray, could you please tell which version is in need.

And I'm using the TIMIT corpus, could this be the source of problem?

Sincerely.

**Comment by dmitriy-serdyuk** [comment]
@Elecky , this project uses its own fork of Theano. You need to remove existing installation of Theano and source the environment `source env.sh`, it will put Theano in PYTHONPATH. To train with CUDA you run it with `THEANO_FLAGS=device=gpu,floatX=float32 ...`.

**Comment by Elecky** [comment]
@dmitriy-serdyuk 
Thank you so much, Maybe that's the reason. I did't noticed that there's another Theano installed in the global environment.
