### ISSUE TITLE
Ask about pretrained model parameters

### ISSUE THREAD

**Issue by ZhichaoWang970201** [rizar/attention-lvcsr#16]
Hi Rizar,
How are your? I want to use transfer learning for future research. Thus, I want to ask if you can provide the final result of parameters like weights and bias.
I am not a CS student. So if you have indeed provided it. So sorry for bothering you.
Thank you very much. Have a very nice day.
Best wishes,
Zhichao

**Comment by rizar** [comment]
sorry, this repo is no longer maintained
