### ISSUE TITLE
How speech frames are organise as input the BiGRU

### ISSUE THREAD

**Issue by trungnt13** [rizar/attention-lvcsr#4]
For most of the task, 1 speech utterance are windowed into many frames (e.g. 25ms log-mel filter-bank), this process result a thousand of frames for utterance, and all these frames need to be input to GRU as a sequence.

Can you give me some hint about how you organize long utterance as input to the network ? Did you split long utterance based on its silent segments ?

For example, [nb_utteranes, nb_frames+padded, 123-log-mel-filter-bank]

**Comment by dmitriy-serdyuk** [comment]
No, we don't split long utterances.

**Comment by rizar** [comment]
Right, we just load thousands of frames into memory, works for us!
